[package]
name = "kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]

[features]
default = ["serial-uart16550"]
serial-uart16550 = []
serial-usart-stm32 = []
